name: Supabase Keep-Alive Cron

on:
  schedule:
    - cron: "0 0 * * 1,4"
  workflow_dispatch:

jobs:
  keep-alive:
    if: ${{ vars.ENABLE_CRON == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create config file
        run: |
          # adjust based on your needs
          echo "[" > config.json
          echo "  {" >> config.json
          echo "    \"name\": \"My Database\"," >> config.json
          echo "    \"supabase_url_env\": \"SUPABASE_URL_1\"," >> config.json
          echo "    \"supabase_key_env\": \"SUPABASE_KEY_1\"," >> config.json
          echo "    \"table_name\": \"keep-alive\"" >> config.json
          echo "  }" >> config.json
          echo "]" >> config.json

      - name: Create .env file
        run: |
          echo "SUPABASE_URL_1='${{ secrets.SUPABASE_URL_1 }}'" > .env
          echo "SUPABASE_KEY_1='${{ secrets.SUPABASE_KEY_1 }}'" > .env

      - name: Run keep-alive script
        run: python main.py
        env:
          SUPABASE_URL_1: ${{ secrets.SUPABASE_URL_1 }}
          SUPABASE_KEY_1: ${{ secrets.SUPABASE_KEY_1 }}

      - name: Upload logs if failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: execution-logs
          path: logfile.log
