name: Supabase Inactive Fix
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'
jobs:
  work:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
    - name: Create config-file
      id: create-config-file
      env:
        CONFIG: ${{ secrets.CONFIG }}
      if: ${{ env.CONFIG != '' }}
      run: |
        touch config.json
        echo "$CONFIG" >> config.json
    - name: Create env-file
      id: Create-env-file
      env:
        ENV: ${{ secrets.ENV }}
      if: ${{ env.ENV != '' }}
      run: |
        touch .env
        echo "$ENV" >> .env
    - name: Run
      id: run
      shell: bash
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        python main.py